### ISSUE TITLE
Add competitive programming problem code 

### ISSUE THREAD

**Issue by thepurpleowl** [thepurpleowl/House-of-Codes#4]
## Guidelines 
- Add a solution in any language in any of the platform(Codechef/Hackerrank/Codeforce etc.)  
- **Always update the README whenever necesary.**
- If platform directory not present make one and put code inside the directory
- Put problem description on the top and add the problem link to README.md in the specific directory

**PR won't be merged unless it follows all the above points.**

**This is an open issue**,  i.e, you need not be assigned to it for contributing. So **GO AHEAD!! No need of questions like** - "Can I add Scala solution to a Hackerrank problem?" OR " May I add solution to Codechef?"

Just make sure to follow folder structure and update the README after adding any code.

**Comment by gaurangisinha** [comment]
Hello, @thepurpleowl I am very keen on contributing to this issue, could you please assign it to me?

**Comment by thepurpleowl** [comment]
Sure, go ahead.

**Comment by Sayantan-world** [comment]
Hey, @thepurpleowl  Can I add c++ codes for Hackerrank problems here?

**Comment by SandeepGamot** [comment]
Hey, this repo is missing LeetCode! 
Should I do the honors?

**Comment by divyadreddy** [comment]
Hello @thepurpleowl, can you please assign this to me

**Comment by thepurpleowl** [comment]
@Sayantan-world yeah go ahead. 

@SandeepGamot  yeah sure. Make a separate repo and add README, and update the README.

**Comment by divyadreddy** [comment]
> Hello @thepurpleowl, can you please assign this to me

Here is the PR - https://github.com/thepurpleowl/House-of-Codes/pull/17

**Comment by divyadreddy** [comment]
> Hello @thepurpleowl, can you please assign this to me

Here is the PR - https://github.com/thepurpleowl/House-of-Codes/pull/17

**Comment by MayankAg20** [comment]
Hello @thepurpleowl , I am adding a program in hackerrank folder

**Comment by xshadowlegendx** [comment]
Hello, may I add solution to problem from open kattis?

**Comment by thepurpleowl** [comment]
> Hello, may I add solution to problem from open kattis?

Yeah sure.

**Comment by xshadowlegendx** [comment]
@thepurpleowl ok thanks

**Comment by varad64** [comment]
Hey @thepurpleowl, can I add Java solution to a Codechef problem?

**Comment by xshadowlegendx** [comment]
@thepurpleowl hello, if I want to add more solutions from open kattis, do I just push more commit and send pull request again that mention this issue?

**Comment by thepurpleowl** [comment]
Push more commit with commit messages containing the issue

**Comment by xshadowlegendx** [comment]
@thepurpleowl ok got it, thanks

**Comment by Isha2208** [comment]
Hey, can you assign the issue to me **@thepurpleowl** . I want to contribute
